### ISSUE TITLE
# missing before "h" in URIs 

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#188]
In many cases in the files, when a URI begins with an "h", there is no hash ("#") before it. For example, `<hBrótaid>` in http://example.com/LL/h_n_echdach.trig. Is this intentional or perhaps the result of a mass find-and-replace gone wrong?

**Comment by cyocum** [comment]
This is a find and replace gone wrong.  Let me know if you see it and I will fix it right away.  I can give you a longer explanation but had to do with the TRiG file conversion and possibly a bug in Stardog.

**Comment by Eystein-Thanisch** [comment]
It's very widespread. Another find-and-replace or similar will be needed to fix it. I can have a go if you like?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Christopher Yocum <notifications@github.com> Date: 18/11/2018  17:57  (GMT+00:00) To: cyocum/irish-gen <irish-gen@noreply.github.com> Cc: Eystein Thanisch <oyysch@googlemail.com>, Author <author@noreply.github.com> Subject: Re: [cyocum/irish-gen] # missing before "h" in URIs  (#188) This is a find and replace gone wrong.  Let me know if you see it and I will fix it right away.  I can give you a longer explanation but had to do with the TRiG file conversion and possibly a bug in Stardog.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cyocum/irish-gen","title":"cyocum/irish-gen","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cyocum/irish-gen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cyocum in #188: This is a find and replace gone wrong.  Let me know if you see it and I will fix it right away.  I can give you a longer explanation but had to do with the TRiG file conversion and possibly a bug in Stardog."}],"action":{"name":"View Issue","url":"https://github.com/cyocum/irish-gen/issues/188#issuecomment-439712178"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cyocum/irish-gen/issues/188#issuecomment-439712178",
"url": "https://github.com/cyocum/irish-gen/issues/188#issuecomment-439712178",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cyocum/irish-gen] # missing before \"h\" in URIs  (#188)",
"sections": [
{
"text": "",
"activityTitle": "**Christopher Yocum**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@cyocum",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cyocum/irish-gen\",\n\"issueId\": 188,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"cyocum/irish-gen\",\n\"issueId\": 188\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cyocum/irish-gen/issues/188#issuecomment-439712178"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 413151291\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by cyocum** [comment]
I caused it so I will fix it :).  I already have the list of culprits so I should have it fixed this evening.  Sorry about this!
