### ISSUE TITLE
Two sections with same number and URL on CELT

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#70]
On CELT's edition of LL, vol. 6, there are two section 123s: H. Maele Cainaig and H. Osráin. The single URL, <http://www.ucc.ie/celt/published/G800011F/text123.html>, leads to H. Maele Cainaig. H. Osráin's URL, in our database, being identical, also leads to H. Maele Cainaig.

**Comment by cyocum** [comment]
After having a look, the actual file names are different but the section links are the same.  Thus if you follow http://www.ucc.ie/celt/published/G800011F/text123.html you will get .H. MAELE CAINAIG. but if you follow http://www.ucc.ie/celt/published/G800011F/text124.html, you will get .H. OSRÁIN.  As we are following the direct file URL and not the section number, we should be fine and they are unique URLs.
