### ISSUE TITLE
Fosterage? 

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#87]
In n_echach.ttl, a fosterage relationship is described (Da mc Echach .i. Crimthand et Lugaid Cichech o tát .h. Lugdech. Is eside ro alt da mc Crimthaind .i. Aed & Loegaire...). Do we want to represent that in the database? I notice that rel:mentorOf already exists. Could we appropriate it?

**Comment by cyocum** [comment]
This already exists in earlyIrishRelationship.ttl ontology. Look in there.  Also, it is already added to most of the files under 

`
@prefix irishRel: <http://example.com/earlyIrishRelationship.ttl#> .
`

Thus you would use it as you would any of the relationship ontology stuff.

**Comment by Eystein-Thanisch** [comment]
Sorry! I am coming back to this after a while and forgot to check there. Thanks!

**Comment by Eystein-Thanisch** [comment]
Actually, how do I view earlyIrishRelationship.ttl ? The link just takes me
to a general page about example domains.

**Comment by cyocum** [comment]
It's just a file in the directory. You should be able to open it on your machine.  Otherwise, you can look here: https://github.com/cyocum/irish-gen/blob/master/earlyIrishRelationship.ttl

**Comment by Eystein-Thanisch** [comment]
Of course. Thanks! Alas, the data science course I went on last week, far
from making me better at this sort of thing, appears to have wiped my
memory...
