### ISSUE TITLE
clanna_ébir_i_l-leith_chuind.ttl not finished

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#88]
Major booby on my part, sorry. clanna_ébir_i_l-leith_chuind.ttl is barely half finished. I have no idea why I stopped where I did. I think it was one of the first I worked on. I'll get it complete and updated to Phase 2 standard asap.

**Comment by cyocum** [comment]
No problem. Just close this ticket when you have finished it. :)

**Comment by cyocum** [comment]
Is this done and can we close this ticket?

**Comment by Eystein-Thanisch** [comment]
Sorry! Yes, it's done. I am not entirely sure how to close the ticket
safely so perhaps you should do it?
